package SephiusEngine.input.controllers.gamepad.maps {


	public class XboxGamepadMapA extends XboxGamepadMap{
		public function XboxGamepadMapA():void{
			super();
			
			WEAPON_1 = BUTTON_X;
			WEAPON_2 = BUTTON_B;
			SPELL_1 = BUTTON_LB;
			SPELL_2 = BUTTON_RB;

			USE_ITEM = BUTTON_X;

			SPELL_RING = LEFT_STICK_CLICK;
			//ITEM_RING = BUTTON_LT;
			WEAPON_RING = RIGHT_STICK_CLICK;

			RINGS = BUTTON_R3;
			RINGS2 = BUTTON_L3;

			RING_SELECTION_1 = RIGHT_STICK;
			RING_SELECTION_2 = LEFT_STICK;
			
			CAMERA = RIGHT_STICK;
			CAMERA_INWARD = RIGHT_STICK_UP;
			CAMERA_OUTWARD = RIGHT_STICK_DOWN;

			FAST_MAP = BUTTON_LT;

			MOVEMENT = DPAD;

			LEFT = DPAD_LEFT;
			RIGHT = DPAD_RIGHT;
			UP = DPAD_UP;
			DOWN = DPAD_DOWN;
			
			TOGGLE_ITEM_LEFT = LEFT_STICK_LEFT;
			TOGGLE_ITEM_RIGHT = LEFT_STICK_RIGHT;
			INTERACTION = LEFT_STICK_UP;
			FAST_MAP = LEFT_STICK_DOWN;

			JUMP = BUTTON_A;
			GLIDING = BUTTON_A;
			ABSORPTION = BUTTON_RT;
			FLY = BUTTON_Y;
			DODGE = BUTTON_Y;
			FLAP_WINGS_A = BUTTON_A;
			
			INTERFACE_UP = DPAD_UP;
			INTERFACE_DOWN = DPAD_DOWN;
			INTERFACE_LEFT = DPAD_LEFT;
			INTERFACE_RIGHT = DPAD_RIGHT;

			INTERFACE_START = BUTTON_START;

			INTERFACE_CONFIRM = BUTTON_A;
			INTERFACE_CANCEL = BUTTON_B;

			INTERFACE_EXIT = BUTTON_B;
			
			INTERFACE_NEXT = BUTTON_RB;
			INTERFACE_PREVIOUS = BUTTON_LB;
			
			INTERFACE_MENU_INFO = BUTTON_BACK;
			
			INTERFACE_PAUSE = BUTTON_START;
		}
	}
}